<?php
return [
    'adminEmail' => 'vikas@eagle4ss.com',
    'phoneCodes' => [
    				'93' =>['min'=>'9' ,'max'=> '9', 'name'=>'Afghanistan', 'zone'=>'Asia/Kabul', 'code'=>'AF'],
					'355'=>['min'=> '3','max'=> '9', 'name'=>'Albania', 'zone'=>'Europe/Tirane', 'code'=>'AL'],
					'213'=>['min'=> '8','max'=> '9', 'name'=>'Algeria', 'zone'=>'Africa/Algiers', 'code'=>'DZ' ],
					'376'=>['min'=> '6','max'=> '9', 'name'=>'Andorra', 'zone'=>'Europe/Andorra', 'code'=>'AD' ],
					'244'=>['min'=> '9','max'=> '9', 'name'=>'Angola', 'zone'=>'Africa/Luanda', 'code'=>'AO' ],
					'54' =>['min'=>'10','max'=> '10', 'name'=>'Argentina', 'zone'=>'America/Argentina/Buenos_Aires', 'code'=>'AR' ],
					'374'=>['min'=> '8','max'=> '8', 'name'=>'Armenia', 'zone'=>'Asia/Yerevan', 'code'=>'AM'],
					'297'=>['min'=> '7','max'=> '7', 'name'=>'America/Aruba', 'zone'=>'Asia/Yerevan', 'code'=>'AW'],
					'61' =>['min'=>'5' ,'max'=> '15', 'name'=>'Australia', 'zone'=>'Australia/Sydney', 'code'=>'AU'],
					'672'=>['min'=> '6','max'=> '6', 'name'=>'Australian External Territories', 'zone'=>'Australia/Sydney', 'code'=>'AU'],
					'43' =>['min'=>'4' ,'max'=> '13', 'name'=>'Austria', 'zone'=>'Europe/Vienna', 'code'=>'AT'],
					'994'=>['min'=> '8','max'=> '9', 'name'=>'Azerbaijan', 'zone'=>'Asia/Baku', 'code'=>'AZ'],
					'973'=>['min'=> '8','max'=> '8', 'name'=>'Bahrain', 'zone'=>'Asia/Bahrain', 'code'=>'BH'],
					'880'=>['min'=> '6','max'=> '10', 'name'=>'Bangladesh', 'zone'=>'Asia/Dhaka', 'code'=>'BD'],
					'375'=>['min'=> '9','max'=> '10', 'name'=>'Belarus', 'zone'=>'Europe/Minsk', 'code'=>'BY'],
					'32' =>['min'=>'8' ,'max'=> '9', 'name'=>'Belgium', 'zone'=>'Europe/Brussels', 'code'=>'BE'],
					'501'=>['min'=> '7','max'=> '7', 'name'=>'Belize', 'zone'=>'America/Belize', 'code'=>'BZ'],
					'229'=>['min'=> '8','max'=> '8', 'name'=>'Benin', 'zone'=>'Africa/Porto-Novo', 'code'=>'BJ'],
					'975'=>['min'=> '7','max'=> '8', 'name'=>'Bhutan', 'zone'=>'Asia/Thimphu', 'code'=>'BT'],
					'591'=>['min'=> '8','max'=> '8', 'name'=>'Bolivia', 'zone'=>'America/La_Paz', 'code'=>'BO'],
					//'599'=>['min'=> '7','max'=> '7', 'name'=>'Bonaire Sint Eustatius and Saba'],
					'387'=>['min'=> '8','max'=> '8', 'name'=>'Bosnia and Herzegovina', 'zone'=>'Europe/Sarajevo', 'code'=>'BA'],
					'267'=>['min'=> '7','max'=> '8', 'name'=>'Botswana', 'zone'=>'Africa/Gaborone', 'code'=>'BW'],
					'55' =>['min'=>'10','max'=> '10', 'name'=>'Brazil', 'zone'=>'America/Fortaleza', 'code'=>'BR'],
					'673'=>['min'=> '7','max'=> '7', 'name'=>'Brunei Darussalam', 'zone'=>'Asia/Brunei', 'code'=>'BN'],
					'359'=>['min'=> '7','max'=> '9', 'name'=>'Bulgaria', 'zone'=>'Europe/Sofia', 'code'=>'BG'],
					'226'=>['min'=> '8','max'=> '8', 'name'=>'Burkina Faso', 'zone'=>'Africa/Ouagadougou', 'code'=>'BF'],
					'257'=>['min'=> '8','max'=> '8', 'name'=>'Burundi', 'zone'=>'Africa/Bujumbura', 'code'=>'BI'],
					'855'=>['min'=> '8','max'=> '8', 'name'=>'Cambodia', 'zone'=>'Asia/Phnom_Penh', 'code'=>'KH'],
					'237'=>['min'=> '8','max'=> '8', 'name'=>'Cameroon', 'zone'=>'Africa/Douala', 'code'=>'CM'],
					'238'=>['min'=> '7','max'=> '7', 'name'=>'Cape Verde', 'zone'=>'Atlantic/Cape_Verde', 'code'=>'CV'],
					'236'=>['min'=> '8','max'=> '8', 'name'=>'Central African Rep', 'zone'=>'Africa/Bangui', 'code'=>'CF'],
					'235'=>['min'=> '8','max'=> '8', 'name'=>'Chad', 'zone'=>'Africa/Ndjamena', 'code'=>'TD'],
					'56' =>['min'=>'8' ,'max'=>'9' , 'name'=>'Chile', 'zone'=>'America/Santiago', 'code'=>'CL'],
					'86' =>['min'=>'5' ,'max'=>'12', 'name'=>'China', 'zone'=>'Asia/Shanghai', 'code'=>'CN'],
					'57' =>['min'=>'8' ,'max'=>'10', 'name'=>'Colombia', 'zone'=>'America/Bogota', 'code'=>'CO'],
					'269'=>['min'=> '7','max'=> '7', 'name'=>'Comoros', 'zone'=>'Indian/Comoro', 'code'=>'KM'],
					'242'=>['min'=> '9','max'=> '9', 'name'=>'Congo', 'zone'=>'Africa/Kinshasa', 'code'=>'CD'],
					'682'=>['min'=> '5','max'=> '5', 'name'=>'Cook Islands', 'zone'=>'Pacific/Rarotonga', 'code'=>'CK'],
					'506'=>['min'=> '8','max'=> '8', 'name'=>'Costa Rica', 'zone'=>'America/Costa_Rica', 'code'=>'CR'],
					'225'=>['min'=> '8','max'=> '8', 'name'=>"Cte d'Ivoire", 'zone'=>'Africa/Abidjan', 'code'=>'CI'],
					'385'=>['min'=> '8','max'=> '12', 'name'=>'Croatia', 'zone'=>'Europe/Zagreb', 'code'=>'HR'],
					'53' =>['min'=>'6' ,'max'=>'8' , 'name'=>'Cuba', 'zone'=>'America/Havana', 'code'=>'CU'],
					'599'=>['min'=> '7','max'=> '8', 'name'=>'Bonaire Sint Eustatius and Saba', 'zone'=>'America/Curacao', 'code' => 'AN'],
					'357'=>['min'=> '8','max'=> '11', 'name'=>'Cyprus', 'zone'=>'Asia/Nicosia', 'code'=>'CY'],
					'420'=>['min'=> '4','max'=> '12', 'name'=>'Czech Rep', 'zone'=>'Europe/Prague', 'code'=>'CZ'],
					'850'=>['min'=> '6','max'=> '17', 'name'=>"Dem. People's Rep. of Korea", 'zone'=>'Africa/Brazzaville', 'code'=>'CG'],
					'243'=>['min'=> '5','max'=> '9', 'name'=>'Dem. Rep. of the Congo', 'zone'=>'Africa/Lubumbashi', 'code'=>'CD'],
					'45' =>['min'=>'8' ,'max'=>'8' , 'name'=>'Denmark', 'zone'=>'Europe/Copenhagen', 'code'=>'DK'],
					'246'=>['min'=> '7','max'=> '7', 'name'=>'Diego Garcia', 'zone'=>'America/Barbados','code' => 'BB'],
					'253'=>['min'=> '6','max'=> '6', 'name'=>'Djibouti', 'zone'=>'Africa/Djibouti', 'code'=>'DJ'],
					'593'=>['min'=> '8','max'=> '8', 'name'=>'Ecuador', 'zone'=>'America/Guayaquil', 'code'=>'EC'],
					'20' =>['min'=>'7' ,'max'=>'9' , 'name'=>'Egypt', 'zone'=>'Africa/Cairo', 'code'=>'EG'],
					'503'=>['min'=> '7','max'=> '11', 'name'=>'El Salvador', 'zone'=>'America/El_Salvador', 'code'=>'SV'],
					'240'=>['min'=> '9','max'=> '9', 'name'=>'Equatorial Guinea', 'zone'=>'Africa/Malabo', 'code'=>'GQ'],
					'291'=>['min'=> '7','max'=> '7', 'name'=>'Eritrea', 'zone'=>'Africa/Asmara', 'code'=>'ER'],
					'372'=>['min'=> '7','max'=> '10', 'name'=>'Estonia', 'zone'=>'Europe/Tallinn', 'code'=>'EE'],
					'251'=>['min'=> '9','max'=> '9', 'name'=>'Ethiopia', 'zone'=>'Africa/Addis_Ababa', 'code'=>'ET'],
					'500'=>['min'=> '5','max'=> '5', 'name'=>'Falkland Islands (Malvinas)', 'zone'=>'Atlantic/Stanley', 'code'=>'FK'],
					'298'=>['min'=> '6','max'=> '6', 'name'=>'Faroe Islands', 'zone'=>'Atlantic/Faroe', 'code'=>'FO'],
					'679'=>['min'=> '7','max'=> '7', 'name'=>'Fiji', 'zone'=>'Pacific/Fiji', 'code'=>'FJ'],
					'358'=>['min'=> '5','max'=> '12', 'name'=>'Finland', 'zone'=>'Europe/Helsinki', 'code'=>'FI'],
					'33' =>['min'=>'9' ,'max'=>'9' , 'name'=>'France', 'zone'=>'Europe/Paris', 'code'=>'FR'],
					'262'=>['min'=> '9','max'=> '9', 'name'=>'French Departments and Territories', 'zone'=>'Indian/Mayotte', 'code' => 'YT'],
					'594'=>['min'=> '9','max'=> '9', 'name'=>'French Guiana', 'zone'=>'America/Cayenne', 'code'=>'GF'],
					'689'=>['min'=> '6','max'=> '6', 'name'=>'French Polynesia', 'zone'=>'Pacific/Tahiti', 'code'=>'PF'],
					'241'=>['min'=> '6','max'=> '7', 'name'=>'Gabon', 'zone'=>'Africa/Libreville', 'code'=>'GA'],
					'220'=>['min'=> '7','max'=> '7', 'name'=>'Gambia', 'zone'=>'Africa/Banjul', 'code'=>'GM'],
					'995'=>['min'=> '9','max'=> '9', 'name'=>'Georgia', 'zone'=>'Asia/Tbilisi', 'code'=>'GE'],
					'49' =>['min'=>'6' ,'max'=>'13', 'name'=>'Germany', 'zone'=>'Europe/Berlin', 'code'=>'DE'],
					'233'=>['min'=> '5','max'=> '9', 'name'=>'Ghana', 'zone'=>'Africa/Accra', 'code'=>'GH'],
					'350'=>['min'=> '8','max'=> '8', 'name'=>'Gibraltar', 'zone'=>'Europe/Gibraltar', 'code'=>'GI'],
					'30' =>['min'=>'10','max'=> '10', 'name'=>'Greece', 'zone'=>'Europe/Athens', 'code'=>'GR'],
					'299'=>['min'=> '6','max'=> '6', 'name'=>'Greenland', 'zone'=>'America/Godthab', 'code'=>'GL'],
					'590'=>['min'=> '9','max'=> '9', 'name'=>'Guadeloupe', 'zone'=>'America/Guadeloupe', 'code'=>'GP'],
					'502'=>['min'=> '8','max'=> '8', 'name'=>'Guatemala', 'zone'=>'America/Guatemala', 'code'=>'GT'],
					'224'=>['min'=> '8','max'=> '8', 'name'=>'Guinea', 'zone'=>'Africa/Conakry', 'code'=>'GN'],
					'245'=>['min'=> '7','max'=> '7', 'name'=>'Guinea-Bissau', 'zone'=>'Africa/Bissau', 'code'=>'GW'],
					'592'=>['min'=> '7','max'=> '7', 'name'=>'Guyana', 'zone'=>'America/Guyana', 'code'=>'GY'],
					'509'=>['min'=> '8','max'=> '8', 'name'=>'Haiti', 'zone'=>'America/Port-au-Prince', 'code'=>'HT'],
					'504'=>['min'=> '8','max'=> '8', 'name'=>'Honduras', 'zone'=>'America/Tegucigalpa', 'code'=>'HN'],
					'852'=>['min'=> '4','max'=> '9', 'name'=>'Hong Kong China', 'zone'=>'Asia/Hong_Kong', 'code'=>'HK'],
					'36' =>['min'=>'8' ,'max'=>'9' , 'name'=>'Hungary', 'zone'=>'Europe/Budapest', 'code'=>'HU'],
					'354'=>['min'=> '7','max'=> '9', 'name'=>'Iceland', 'zone'=>'Atlantic/Reykjavik', 'code'=>'IS'],
					'91' =>['min'=>'10','max'=>'10' , 'name'=>'India', 'zone'=>'Asia/Kolkata', 'code'=>'IN'],
					'62' =>['min'=>'5' ,'max'=>'10', 'name'=>'Indonesia', 'zone'=>'Asia/Jakarta', 'code'=>'ID'],
					'870'=>['min'=> '9','max'=> '9', 'name'=>'Inmarsat SNAC', 'zone'=> 'Pacific/Pitcairn', 'code'=>'PN'],
					//'800'=>['min'=> '8','max'=> '8', 'name'=>'International Freephone Service'],
					//'882'=>['min'=> '0','max'=> '0', 'name'=>'International Networks shared code' ],
					//'883'=>['min'=> '0','max'=> '0', 'name'=>'International Networks shared code' ],
					//'979'=>['min'=> '9','max'=> '9', 'name'=>'International Premium Rate Service'],
					'808'=>['min'=> '8','max'=> '8', 'name'=>'International Shared Cost Service', 'zone'=>'Pacific/Midway', 'code' =>''],
					'98' =>['min'=>'6' ,'max'=>'10', 'name'=>'Iran', 'zone'=>'Asia/Tehran', 'code'=>'IR'],
					'964'=>['min'=> '8','max'=> '10', 'name'=>'Iraq', 'zone'=>'Asia/Baghdad', 'code'=>'IQ'],
					'353'=>['min'=> '7','max'=> '11', 'name'=>'Ireland', 'zone'=>'Europe/Dublin', 'code'=>'IE'],
					'972'=>['min'=> '8','max'=> '9', 'name'=>'Israel', 'zone'=>'Asia/Jerusalem', 'code'=>'IL'],
					'39' =>['min'=>'1' ,'max'=>'11', 'name'=>'Italy', 'zone'=>'Europe/Rome', 'code'=>'IT'],
					'81' =>['min'=>'5' ,'max'=>'13', 'name'=>'Japan', 'zone'=>'Asia/Tokyo', 'code'=>'JP'],
					'962'=>['min'=> '5','max'=> '9', 'name'=>'Jordan', 'zone'=>'Asia/Amman', 'code'=>'JO'],
					'7'  =>['min'=>'10' ,'max'=>'10', 'name'=>'Kazakhstan', 'zone'=>'Asia/Almaty', 'code'=>'KZ'],
					'254'=>['min'=> '6','max'=> '10', 'name'=>'Kenya', 'zone'=>'Africa/Nairobi', 'code'=>'KE'],
					'686'=>['min'=> '5','max'=> '5', 'name'=>'Kiribati', 'zone'=>'Pacific/Tarawa', 'code'=>'KI'],
					'82' =>['min'=>'8' ,'max'=>'11', 'name'=>'Korea', 'zone'=>'Asia/Pyongyang', 'code'=>'KP'],
					'965'=>['min'=> '7','max'=> '8', 'name'=>'Kuwait', 'zone'=>'Asia/Kuwait', 'code'=>'KW'],
					'996'=>['min'=> '9','max'=> '9', 'name'=>'Kyrgyzstan', 'zone'=>'Asia/Bishkek', 'code'=>'KG'],
					'856'=>['min'=> '8','max'=> '10', 'name'=>'Lao P.D.R.', 'zone'=>'Asia/Vientiane', 'code'=>'LA'],
					'371'=>['min'=> '7','max'=> '8', 'name'=>'Latvia', 'zone'=>'Europe/Riga', 'code'=>'LV'],
					'961'=>['min'=> '7','max'=> '8', 'name'=>'Lebanon', 'zone'=>'Asia/Beirut', 'code'=>'LB'],
					'266'=>['min'=> '8','max'=> '8', 'name'=>'Lesotho', 'zone'=>'Africa/Maseru', 'code'=>'LS'],
					'231'=>['min'=> '7','max'=> '8', 'name'=>'Liberia', 'zone'=>'Africa/Monrovia', 'code'=>'LR'],
					'218'=>['min'=> '8','max'=> '9', 'name'=>'Libya', 'zone'=>'Africa/Tripoli', 'code'=>'LY'],
					'423'=>['min'=> '7','max'=> '9', 'name'=>'Liechtenstein', 'zone'=>'Europe/Vaduz', 'code'=>'LI'],
					'370'=>['min'=> '8','max'=> '8', 'name'=>'Lithuania', 'zone'=>'Europe/Vilnius', 'code'=>'LT'],
					'352'=>['min'=> '4','max'=> '11', 'name'=>'Luxembourg', 'zone'=>'Europe/Luxembourg', 'code'=>'LU'],
					'853'=>['min'=> '7','max'=> '8', 'name'=>'Macao China', 'zone'=>'Asia/Urumqi', 'code'=>'CN'],
					'261'=>['min'=> '9','max'=> '10', 'name'=>'Madagascar', 'zone'=>'Indian/Antananarivo', 'code'=>'MG'],
					'265'=>['min'=> '7','max'=> '8', 'name'=>'Malawi', 'zone'=>'Africa/Blantyre', 'code'=>'MW'],
					'60' =>['min'=>'7' ,'max'=>'9' , 'name'=>'Malaysia', 'zone'=>'Asia/Kuala_Lumpur', 'code'=>'MY'],
					'960'=>['min'=> '7','max'=> '7', 'name'=>'Maldives', 'zone'=>'Indian/Maldives', 'code'=>'MV'],
					'223'=>['min'=> '8','max'=> '8', 'name'=>'Mali', 'zone'=>'Africa/Bamako', 'code'=>'ML'],
					'356'=>['min'=> '8','max'=> '8', 'name'=>'Malta', 'zone'=>'Europe/Malta', 'code'=>'MT'],
					'692'=>['min'=> '7','max'=> '7', 'name'=>'Marshall Islands', 'zone'=>'Pacific/Majuro', 'code'=>'MH'],
					'596'=>['min'=> '9','max'=> '9', 'name'=>'Martinique', 'zone'=>'America/Martinique', 'code'=>'MQ'],
					'222'=>['min'=> '7','max'=> '7', 'name'=>'Mauritania', 'zone'=>'Africa/Nouakchott', 'code'=>'MR'],
					'230'=>['min'=> '7','max'=> '7', 'name'=>'Mauritius', 'zone'=>'Indian/Mauritius', 'code'=>'MU'],
					'52' =>['min'=>'10','max'=> '10', 'name'=>'Mexico', 'zone'=>'America/Mexico_City', 'code'=>'MX'],
					'691'=>['min'=> '7','max'=> '7', 'name'=>'Micronesia', 'zone'=>'Pacific/Chuuk', 'code'=>'FM'],
					'373'=>['min'=> '8','max'=> '8', 'name'=>'Moldova', 'zone'=>'Europe/Chisinau', 'code'=>'MD'],
					'377'=>['min'=> '5','max'=> '9', 'name'=>'Monaco', 'zone'=>'Europe/Monaco', 'code'=>'MC'],
					'976'=>['min'=> '7','max'=> '8', 'name'=>'Mongolia', 'zone'=>'Asia/Ulaanbaatar', 'code'=>'MN'],
					'382'=>['min'=> '4','max'=> '12', 'name'=>'Montenegro', 'zone'=>'Europe/Podgorica', 'code'=>'ME'],
					'212'=>['min'=> '9','max'=> '9', 'name'=>'Morocco', 'zone'=>'Africa/Casablanca', 'code'=>'MA'],
					'258'=>['min'=> '8','max'=> '9', 'name'=>'Mozambique', 'zone'=>'Africa/Maputo', 'code'=>'MZ'],
					'95' =>['min'=>'7' ,'max'=>'9' , 'name'=>'Myanmar', 'zone'=>'Asia/Rangoon', 'code'=>'MM'],
					'264'=>['min'=> '6','max'=> '10', 'name'=>'Namibia', 'zone'=>'Africa/Windhoek', 'code'=>'NA'],
					'674'=>['min'=> '4','max'=> '7', 'name'=>'Nauru', 'zone'=>'Pacific/Nauru', 'code'=>'NR'],
					'977'=>['min'=> '8','max'=> '9', 'name'=>'Nepal', 'zone'=>'Asia/Kathmandu', 'code'=>'NP'],
					'31' =>['min'=>'9' ,'max'=>'9' , 'name'=>'Netherlands', 'zone'=>'Europe/Amsterdam', 'code'=>'NL'],
					'687'=>['min'=> '6','max'=> '6', 'name'=>'New Caledonia', 'zone'=>'Pacific/Noumea', 'code'=>'NC'],
					'64' =>['min'=>'3' ,'max'=>'10', 'name'=>'New Zealand', 'zone'=>'Pacific/Auckland', 'code'=>'NZ'],
					'505'=>['min'=> '8','max'=> '8', 'name'=>'Nicaragua', 'zone'=>'America/Managua', 'code'=>'NI'],
					'227'=>['min'=> '8','max'=> '8', 'name'=>'Niger', 'zone'=>'Africa/Niamey', 'code'=>'NE'],
					'234'=>['min'=> '7','max'=> '10', 'name'=>'Nigeria', 'zone'=>'Africa/Lagos', 'code'=>'NG'],
					'683'=>['min'=> '4','max'=> '4', 'name'=>'Niue', 'zone'=>'Pacific/Niue', 'code'=>'NU'],
					'47' =>['min'=>'5' ,'max'=>'8' , 'name'=>'Norway', 'zone'=>'Europe/Oslo', 'code'=>'NO'],
					'968'=>['min'=> '7','max'=> '8', 'name'=>'Oman', 'zone'=>'Asia/Muscat', 'code'=>'OM'],
					'92' =>['min'=>'8' ,'max'=>'11', 'name'=>'Pakistan', 'zone'=>'Asia/Karachi', 'code'=>'PK'],
					'680'=>['min'=> '7','max'=> '7', 'name'=>'Palau', 'zone'=>'Pacific/Palau', 'code'=>'PW'],
					'507'=>['min'=> '7','max'=> '8', 'name'=>'Panama', 'zone'=>'America/Panama', 'code'=>'PA'],
					'675'=>['min'=> '4','max'=> '11', 'name'=>'Papua New Guinea', 'zone'=>'Pacific/Port_Moresby', 'code'=>'PG'],
					'595'=>['min'=> '5','max'=> '9', 'name'=>'Paraguay', 'zone'=>'America/Asuncion', 'code'=>'PY'],
					'51' =>['min'=>'8' ,'max'=>'11', 'name'=>'Peru', 'zone'=>'America/Lima', 'code'=>'PE'],
					'63' =>['min'=>'8' ,'max'=>'10', 'name'=>'Philippines', 'zone'=>'Asia/Manila', 'code'=>'PH'],
					'48' =>['min'=>'6' ,'max'=>'9' , 'name'=>'Poland', 'zone'=>'Europe/Warsaw', 'code'=>'PL'],
					'351'=>['min'=> '9','max'=> '11', 'name'=>'Portugal', 'zone'=>'Europe/Lisbon', 'code'=>'PT'],
					'974'=>['min'=> '3','max'=> '8', 'name'=>'Qatar', 'zone'=>'Asia/Qatar', 'code'=>'QA'],
					'40' =>['min'=>'9' ,'max'=>'9' , 'name'=>'Romania', 'zone'=>'Europe/Bucharest', 'code'=>'RO'],
					'7'  =>['min'=>'10' ,'max'=>'10', 'name'=>'Russian Federation', 'zone'=>'Europe/Moscow','code' => 'RU'],
					'250'=>['min'=> '9','max'=> '9', 'name'=>'Rwanda', 'zone'=>'Africa/Kigali', 'code'=>'RW'],
					//'247'=>['min'=> '4','max'=> '4', 'name'=>'Saint Helena Ascension and Tristan da Cunha' ],
					'290'=>['min'=> '4','max'=> '4', 'name'=>'Saint Helena Ascension and Tristan da Cunha', 'zone'=>'Atlantic/St_Helena', 'code'=>'SH'],
					'508'=>['min'=> '6','max'=> '6', 'name'=>'Saint Pierre and Miquelon', 'zone' => 'America/Miquelon', 'code'=>'PM'],
					'685'=>['min'=> '3','max'=> '7', 'name'=>'Samoa', 'zone'=>'Pacific/Apia', 'code'=>'WS'],
					'378'=>['min'=> '6','max'=> '10', 'name'=>'San Marino', 'zone'=>'Europe/San_Marino', 'code'=>'SM'],
					'239'=>['min'=> '7','max'=> '7', 'name'=>'Sao Tome and Principe', 'zone'=>'Africa/Sao_Tome', 'code'=>'ST'],
					'966'=>['min'=> '8','max'=> '9', 'name'=>'Saudi Arabia', 'zone'=>'Asia/Riyadh', 'code'=>'SA'],
					'221'=>['min'=> '9','max'=> '9', 'name'=>'Senegal', 'zone'=>'Africa/Dakar', 'code'=>'SN'],
					'381'=>['min'=> '4','max'=> '12', 'name'=>'Serbia', 'zone'=>'Europe/Belgrade', 'code'=>'RS'],
					'248'=>['min'=> '7','max'=> '7', 'name'=>'Seychelles', 'zone'=>'Indian/Mahe', 'code'=>'SC'],
					'232'=>['min'=> '8','max'=> '8', 'name'=>'Sierra Leone', 'zone'=>'Africa/Freetown', 'code'=>'SL'],
					'65' =>['min'=>'8' ,'max'=>'12', 'name'=>'Singapore', 'zone'=>'Asia/Singapore', 'code'=>'SG'],
					'421'=>['min'=> '4','max'=> '9', 'name'=>'Slovakia', 'zone'=>'Europe/Bratislava', 'code'=>'SK'],
					'386'=>['min'=> '8','max'=> '8', 'name'=>'Slovenia', 'zone'=>'Europe/Ljubljana', 'code'=>'SI'],
					'677'=>['min'=> '5','max'=> '5', 'name'=>'Solomon Islands', 'zone'=>'Pacific/Guadalcanal', 'code'=>'SB'],
					'252'=>['min'=> '5','max'=> '8', 'name'=>'Somalia', 'zone'=>'Africa/Mogadishu', 'code'=>'SO'],
					'27' =>['min'=>'9' ,'max'=>'9' , 'name'=>'South Africa', 'zone'=>'Africa/Johannesburg', 'code'=>'ZA'],
					'211'=>['min'=> '1','max'=> '15', 'name'=>'South Sudan', 'zone'=>'Africa/Juba', 'code'=>'SS' ],
					'34' =>['min'=>'9' ,'max'=>'9' , 'name'=>'Spain', 'zone'=>'Europe/Madrid', 'code'=>'ES'],
					'94' =>['min'=>'9' ,'max'=>'9' , 'name'=>'Sri Lanka', 'zone'=>'Asia/Colombo', 'code'=>'LK'],
					'249'=>['min'=> '9','max'=> '9', 'name'=>'Sudan', 'zone'=>'Africa/Khartoum', 'code'=>'SD'],
					'597'=>['min'=> '6','max'=> '7', 'name'=>'Suriname', 'zone'=>'America/Paramaribo', 'code'=>'SR'],
					'268'=>['min'=> '7','max'=> '8', 'name'=>'Swaziland', 'zone'=>'Africa/Mbabane', 'code'=>'SZ' ],
					'46' =>['min'=>'7' ,'max'=>'13', 'name'=>'Sweden', 'zone'=>'Europe/Stockholm', 'code'=>'SE'],
					'41' =>['min'=>'4' ,'max'=>'12', 'name'=>'Switzerland','zone'=>'Europe/Zurich', 'code'=>'CH'],
					'963'=>['min'=> '8','max'=> '10', 'name'=>'Syrian Arab Republic', 'zone' => 'Asia/Damascus', 'code'=>'SY'],
					'886'=>['min'=> '8','max'=> '9', 'name'=>'Taiwan China','zone'=>'Asia/Taipei', 'code'=>'TW'],
					'992'=>['min'=> '9','max'=> '9', 'name'=>'Tajikistan', 'zone'=>'Asia/Dushanbe', 'code'=>'TJ'],
					'255'=>['min'=> '9','max'=> '9', 'name'=>'Tanzania', 'zone'=>'Africa/Dar_es_Salaam', 'code'=>'TZ'],
					//'888'=>['min'=> '1','max'=> '15', 'name'=>'Telecommunications for Disaster Relief'],
					'66' =>['min'=>'8' ,'max'=>'9' , 'name'=>'Thailand','zone'=>'Asia/Bangkok', 'code'=>'TH'],
					'389'=>['min'=> '8','max'=> '9', 'name'=>'The Former Yugoslav Republic of Macedonia','zone'=>'Europe/Skopje', 'code'=>'MK'],
					'670'=>['min'=> '7','max'=> '7', 'name'=>'Timor-Leste','zone'=>'Asia/Dili', 'code'=>'TL'],
					'228'=>['min'=> '8','max'=> '8', 'name'=>'Togo','zone'=>'Africa/Lome', 'code'=>'TG'],
					'690'=>['min'=> '4','max'=> '4', 'name'=>'Tokelau','zone'=>'Pacific/Fakaofo', 'code'=>'TK'],
					'676'=>['min'=> '5','max'=> '7', 'name'=>'Tonga','zone'=>'Pacific/Tongatapu', 'code'=>'TO'],
					//'991'=>['min'=> '1','max'=> '15', 'name'=>'Trial of a proposed new international service shared code' ],
					'216'=>['min'=> '8','max'=> '8', 'name'=>'Tunisia','zone'=>'Africa/Tunis', 'code'=>'TN'],
					'90' =>['min'=>'10','max'=> '10', 'name'=>'Turkey','zone'=>'Europe/Istanbul', 'code'=>'TR'],
					'993'=>['min'=> '8','max'=> '8', 'name'=>'Turkmenistan','zone'=>'Asia/Ashgabat', 'code'=>'TM'],
					'688'=>['min'=> '5','max'=> '6', 'name'=>'Tuvalu','zone'=>'Pacific/Funafuti', 'code'=>'TV'],
					'256'=>['min'=> '9','max'=> '9', 'name'=>'Uganda','zone'=>'Africa/Kampala', 'code'=>'UG'],
					'380'=>['min'=> '9','max'=> '9', 'name'=>'Ukraine','zone'=>'Europe/Kiev', 'code'=>'UA'],
					'971'=>['min'=> '8','max'=> '9', 'name'=>'United Arab Emirates','zone'=>'Asia/Dubai', 'code'=>'AE'],
					'44' =>['min'=>'7' ,'max'=>'10', 'name'=>'United Kingdom', 'zone'=>'Europe/London', 'code'=>''],
					'1'  =>['min'=>'10' ,'max'=>'10', 'name'=>'United States','zone'=>'America/New_York', 'code'=>'US'],
					//'878'=>['min'=> '1','max'=> '15', 'name'=>'Universal Personal Telecommunication' ],
					'598'=>['min'=> '4','max'=> '11', 'name'=>'Uruguay','zone'=>'America/Montevideo', 'code'=>'UY'],
					'998'=>['min'=> '9','max'=> '9', 'name'=>'Uzbekistan','zone'=>'Asia/Samarkand', 'code'=>'UZ'],
					'678'=>['min'=> '5','max'=> '7', 'name'=>'Vanuatu','zone'=>'Pacific/Efate', 'code'=>'VU'],
					'39' =>['min'=>'1' ,'max'=>'11', 'name'=>'Vatican','zone'=>'Europe/Vatican', 'code'=>'VA'],
					'379'=>['min'=> '1','max'=> '11', 'name'=>'Vatican','zone'=>'Europe/Vatican', 'code'=>'VA'],
					'58' =>['min'=>'10','max'=> '10', 'name'=>'Venezuela','zone'=>'America/Caracas', 'code'=>'VE'],
					'84' =>['min'=>'7' ,'max'=>'10', 'name'=>'Vietnam','zone'=>'Asia/Ho_Chi_Minh', 'code'=>'VN'],
					'681'=>['min'=> '6','max'=> '6', 'name'=>'Wallis and Futuna','zone'=>'Pacific/Wallis', 'code'=>'WF'],
					'967'=>['min'=> '6','max'=> '9', 'name'=>'Yemen','zone'=>'Asia/Aden', 'code'=>'YE'],
					'260'=>['min'=> '9','max'=> '9', 'name'=>'Zambia','zone'=>'Africa/Lusaka', 'code'=>'ZM'],
					'263'=>['min'=> '5','max'=> '10', 'name'=>'Zimbabwe','zone'=>'Africa/Harare', 'code'=>'ZW']
					],
];
